include(
    ":android:app",
    ":android:features:idol",
    ":android:widget",
    ":web:app",
    ":shared:components:core",
    ":shared:domain:valueobject",
    ":shared:infra:repository",
    ":shared:infra:query",
    ":shared:infra:api"
)
