name: "[JVM/Web] Unit Test"

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 11
      - uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run test on JVM
        run: ./gradlew testDebugUnitTest --stacktrace testDebugUnitTestReport --stacktrace
      - name: Run test on JS
        run: ./gradlew jsNodeTest --stacktrace jsNodeTestReport --stacktrace
      - name: Archive test on JVM results artifact
        uses: actions/upload-artifact@master
        with:
          name: all-jvm-test-reports
          path: ./build/reports/allTests/testDebugUnitTest
      - name: Archive test on JS results artifact
        uses: actions/upload-artifact@master
        with:
          name: all-js-test-reports
          path: ./build/reports/allTests/jsNodeTest
