name: "[Web] Build and Deploy"

on:
  push:
    tags: [web/v*]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build for production with Gradle
        run: ./gradlew :web:app:jsBrowserProductionWebpack --stacktrace
      - name: Archive production artifacts
        uses: actions/upload-artifact@master
        with:
          name: web-app-artfacts
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup node with 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: web-app-artfacts
          path: ./public
      - name: Install firebase-tools
        run: yarn global add firebase-tools
      - name: Deploy to Firebase
        run: $(yarn global bin)/firebase deploy --token $FIREBASE_TOKEN --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


